# Generated by Django 5.2.7 on 2025-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'actualité")),
                ('description', models.TextField(verbose_name='Contenu ou description')),
                ('image', models.ImageField(upload_to='actualites/', verbose_name="Image illustrant l'actualité")),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('niveau_formation', models.CharField(choices=[('prescolaire', 'Préscolaire'), ('fondamental_I', 'Fondamental I'), ('fondamental_II', 'Fondamental II'), ('fondamental_III', 'Fondamental III'), ('secondaire', 'Secondaire')], max_length=50)),
                ('niveau_etude', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('acte_naissance', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('photo_identite', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('carte_vaccination', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('carnet_pdf', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('bulletin_pdf', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('nisu', models.CharField(blank=True, max_length=50, null=True)),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('paiement_pdf', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
